export type GameState = {
  moveSpeed: number,
  reloadSpeed: number,
  reloadMovePenalty: number,
  maxHealth: number,
  cooldown: number,
  luck: number,
  wave: number,
  gold: number,
  xp: number,
  level: number,
  xpToLevel: number,
  playerHealth: number,
  enemyDamageCooldownMs: number,
  waves: Array<Array<{ type: "red" | "blue", count: number }>>,
};

export const gameState: GameState = {
  moveSpeed: 360,
  reloadSpeed: 1.0,
  reloadMovePenalty: 0.5,
  maxHealth: 5,
  cooldown: 0,
  luck: 1.0,
  wave: 1,
  gold: 0,
  xp: 0,
  level: 1,
  xpToLevel: 10,
  playerHealth: 5,
  enemyDamageCooldownMs: 1000,
  waves: [
    [{ type: "red", count: 5 }],
    [{ type: "red", count: 6 }, { type: "blue", count: 1 }],
    [{ type: "red", count: 6 }, { type: "blue", count: 2 }],
  ],
};
